variable "grpc_config" {
  description = "(optional) - The full text of the Service Config YAML file (Example located here). If provided, must also provide protoc_output_base64. open_api config must not be provided."
  type        = string
  default     = null
}

variable "openapi_config" {
  description = "(optional) - The full text of the OpenAPI YAML configuration as described here. Either this, or both of grpc_config and protoc_output_base64 must be specified."
  type        = string
  default     = null
}

variable "project" {
  description = "(optional) - The project ID that the service belongs to. If not provided, provider project is used."
  type        = string
  default     = null
}

variable "protoc_output_base64" {
  description = "(optional) - The full contents of the Service Descriptor File generated by protoc. This should be a compiled .pb file, base64-encoded."
  type        = string
  default     = null
}

variable "service_name" {
  description = "(required) - The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog."
  type        = string
}

variable "timeouts" {
  description = "nested mode: NestingSingle, min items: 0, max items: 0"
  type = set(object(
    {
      create = string
      delete = string
      update = string
    }
  ))
  default = []
}

